export const COPY = {
  startLesson: "Start Lesson",
  resumeLesson: "Continue Lesson",
  submitAnswer: "Submit Answer",
  continueConcept: "Continue Lesson",
  finishConcept: "Finish Concept",
  takeBreak: "Take a Break",
  returnToLesson: "Return to Lesson",
  tryAgain: "Try Again",
  goHome: "Go to Home",
  startTodaysLesson: "Start Today's Lesson",
  backToSubjects: "Back to subjects",
  backToChapters: "Back to chapters",
  chooseSubject: "Choose a Subject",
  selectSubject: "Select a subject to start learning",
  chooseConcept: "Choose a Concept",
  selectConcept: "Select a concept to start learning",
  loadingSubjects: "Finding lessons\u2026",
  loadingConcepts: "Finding concepts\u2026",
  loadingChapters: "Finding chapters\u2026",
  loadingLesson: "Loading lesson\u2026",
  conceptNotFound: "We can't find that lesson",
  noSubjectsYet: "No subjects yet",
  noChapters: "No chapters yet",
  noConcepts: "No concepts yet",
  errorTitle: "Something went wrong",
  errorBody: "We can't load this right now. Please try again.",
  resumableSession: "You have a lesson in progress",
  lastStep: "Last step: {step}",
  loadingProgress: "Loading progress...",
  loadingReports: "Loading reports...",
} as const;
