/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./lib/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    fontFamily: {
      sans: ["var(--font-inter)", "system-ui", "sans-serif"],
    },
    spacing: {
      1: "8px",
      2: "16px",
      3: "24px",
      4: "32px",
      5: "40px",
      6: "48px",
      7: "56px",
      8: "64px",
      9: "72px",
      10: "80px",
    },
    borderRadius: {
      sm: "4px",
      DEFAULT: "8px",
      md: "12px",
      lg: "16px",
      xl: "24px",
      full: "9999px",
    },
    extend: {
      colors: {
        primary: "#335f87",
        "on-primary": "#ffffff",
        "primary-container": "#4e78a1",
        secondary: "#36656e",
        "on-secondary": "#ffffff",
        "secondary-container": "#baebf5",
        tertiary: "#3e6447",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#567e5e",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        surface: "#fbf9f4",
        "on-surface": "#1b1c19",
        "on-surface-variant": "#42474e",
        outline: "#72777f",
        "outline-variant": "#c2c7cf",
        "soft-blue": "var(--color-soft-blue)",
        "muted-teal": "#76A5AF",
        "muted-green": "#8FB996",
        "soft-amber": "#EBC06D",
        "soft-coral": "#E5989B",
        "warm-off-white": "#F9F7F2",
        "slate-text": "var(--color-slate-text)",
      },
    },
  },
  plugins: [],
};
